name: dragonsapprentice
summary: Use code blocks to move objects in the world and program allies
description: |
  An evil force has spread its way across the land of Ovun and is threatening to destroy this peaceful city. Explore hidden temples, learn magic runes that let you program and control the elements around you, and battle the shadow fiends. Find all the keys in the Dragon Temples to awaken the dragon. Be the hero that Ovun needs!
version: '1.1'
base: core22
architectures:
- amd64
confinement: strict
grade: stable

apps:
  dragonsapprentice:
    extensions: [gnome]
    command: /DragonsApprentice/DragonsApprentice.x64
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - joystick
      - network
      - opengl
      - wayland
      - x11

parts:
  dragonsapprentice:
    source: https://github.com/endless-network/DragonsApprentice_Binary/releases/download/v1.1/DragonsApprentice.zip
    plugin: dump
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/DragonsApprentice/DragonsApprentice.x64
  desktop-files:
    plugin: nil
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui
